### ISSUE TITLE
Images and SVGs

### ISSUE THREAD

**Issue by gazpachu** [DimitriMikadze/express-react-redux-starter#5]
Hi Dimitri,

Thanks for this nice boilerplate. I have a question. Where would you put the images and SVGs to make them work for both environment, dev and production.

Thanks

**Comment by DimiMikadze** [comment]
Hey gazpachu,

Thanks! 

just updated repository, you can put images and static files in root directory static folder.

and then use it, for example src='/static/image.svg'

**Comment by gazpachu** [comment]
But in production, the server is running inside '/dist', therefore it won't find the images in '/static', isn't it?

**Comment by DimiMikadze** [comment]
It will, because express static middleware is configured for /dist and root ./ directory also.
you can take a look at server.js 
https://github.com/DimitriMikadze/express-react-redux-starter/blob/master/server.js

this small app is running on production and client side is using this starter repo.

https://github.com/DimitriMikadze/node-redux-auth

**Comment by gazpachu** [comment]
ok, cool. Thanks!
